# Generated by Django 6.0.2 on 2026-03-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_medicine_patient_deleted_at_patient_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
