# Generated by Django 6.0.2 on 2026-04-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_medicine_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
