# Generated by Django 6.0.2 on 2026-04-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_doctor_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Maintenance', 'Maintenance'), ('Broken', 'Broken')], default='Available', max_length=20)),
                ('last_maintained', models.DateTimeField(auto_now_add=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='CareTrack Healthcare', max_length=200)),
                ('hospital_address', models.TextField(default='123 Care Avenue, Medical District')),
                ('contact_email', models.EmailField(default='contact@caretrack.com', max_length=254)),
                ('contact_phone', models.CharField(default='+1 234 567 8900', max_length=20)),
            ],
        ),
    ]
